[build]
  command = """
    apt-get install portaudio19-dev python-all-dev && cd careerbuddy-frontend && npm install && npm run build
  """
  publish = "careerbuddy-frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-cache-npm"

[[plugins]]
  package = "netlify-plugin-cache-pip"

[[build.packages]]
  apt = ["portaudio19-dev"]
