[build]
  command = """
    curl -O https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz
    tar -xf Python-3.12.0.tgz
    cd Python-3.12.0
    ./configure --enable-optimizations
    make -j $(nproc)
    sudo make altinstall
    cd ..
    python3.12 -m venv venv
    . venv/bin/activate
    pip install --upgrade pip
    pip install wheel
    pip install -r requirements.txt
    cd careerbuddy-frontend && npm install && npm run build
  """
  publish = "careerbuddy-frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-cache-npm"

[[plugins]]
  package = "netlify-plugin-cache-pip"

[build.environment]
  PYTHON_VERSION = "3.12.0"