[build]
  command = """
    cd careerbuddy-frontend && npm install && npm run build
  """
  publish = "careerbuddy-frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-cache-pip"

[[plugins]]
  package = "netlify-plugin-cache-npm"

[build.environment]
  PIP_CACHE_DIR = ".pip_cache"